---
config:
  layout: fixed
---
flowchart TD
    node101["Router"] -- "Link Type -Wi-FiConnection Qualitity -Good" --> node102{{"Mesh"}}
    node102 -- "Link Type -Wi-FiConnection Qualitity -Good" --> node103{{"Mesh"}} & node104{{"Mesh"}}
    node101 -- "Link Type -Wi-Fi / Connection Qualitity -98" --> node105("Unknown-f0:b0:40:15:66:bc")
    node102 -- "Link Type -Wi-Fi / Connection Qualitity -98" --> node109("Ross-iPhone")
    node103 -- "Link Type -Wi-Fi / Connection Qualitity -184" --> node110("SonosZP")
    node103 -- "Link Type -Wi-Fi / Connection Qualitity -64" --> node111("SonosZP-3")
    node103 -- "Link Type -Wi-Fi / Connection Qualitity -86" --> node112("Unknown-48:e1:e9:4a:1a:5b")
    node103 -- "Link Type -Wi-Fi / Connection Qualitity -92" --> node113("09AC01AC30200314")
    node103 -- "Link Type -Wi-Fi / Connection Qualitity -76" --> node114("Carolines-MBP")
    node103 -- "Link Type -Wi-Fi / Connection Qualitity -110" --> node115("SonosZP-2")
    node103 -- "Link Type -Wi-Fi / Connection Qualitity -108" --> node116("iPhone-2")
    node103 -- "Link Type -Wi-Fi / Connection Qualitity -96" --> node117("Unknown-44:3d:54:1e:d3:71")
    node103 -- "Link Type -Wi-Fi / Connection Qualitity -84" --> node118("Samsung")
    node104 -- "Link Type -Wi-Fi / Connection Qualitity -132" --> node119("Unknown-90:39:5f:c4:96:07")
    node104 -- "Link Type -Wi-Fi / Connection Qualitity -138" --> node120("LGwebOSTV")
    node104 -- "Link Type -Wi-Fi / Connection Qualitity -80" --> node121("Unknown-48:e1:e9:4a:1b:b3")
    node104 -- "Link Type -Wi-Fi / Connection Qualitity -106" --> node122("SonosZP-5")
    node104 -- "Link Type -Wi-Fi / Connection Qualitity -146" --> node123("SonosZP-4")
    node104 -- "Link Type -Wi-Fi / Connection Qualitity -134" --> node124("Unknown-48:e1:e9:4a:1b:41")
    node104 -- "Link Type -Wi-Fi / Connection Qualitity -94" --> node125("SonosZP-8")
    node104 -- "Link Type -Wi-Fi / Connection Qualitity -92" --> node126("Unknown-48:e1:e9:4a:1c:cc")
